export { Hero } from './hero/Hero'
export { MainSection } from './mainSection/MainSection'
export { Sales } from './sales/Sales'
export { Stories } from './stories/Stories'
export { Footer } from './footer/Footer'
export { Navbar } from './navbar/Navbar'
export { Cart } from './cart/Cart'
